In [1]:
import numpy as np
import pandas as pd

## Qn 1:

In [18]:
array1 = np.array([[1,2,3],[4,5,6]])

In [19]:
array1.shape

(2, 3)

In [20]:
array1.ndim

2

## Qn 2:

In [5]:
array2 = np.arange(20)

In [6]:
array2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
array2[10:16]

array([10, 11, 12, 13, 14, 15])

## Qn 3:

In [9]:
array3 =np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30],[31,32,33,34,35]])

In [10]:
array4 =np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30],[31,32,33,34,35]])

In [11]:
array3 + array4

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50],
       [52, 54, 56, 58, 60],
       [62, 64, 66, 68, 70]])

In [12]:
array3 * array4

array([[   1,    4,    9,   16,   25],
       [  36,   49,   64,   81,  100],
       [ 121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400],
       [ 441,  484,  529,  576,  625],
       [ 676,  729,  784,  841,  900],
       [ 961, 1024, 1089, 1156, 1225]])

In [13]:
array3 - array4


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [14]:
array3 / array4

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Qn 4:

In [15]:
array5 = np.array([[1,2],[3,4]])

In [16]:
array6 = np.array([[5,6,7],[8,9,10]])

In [17]:
array5 * array6

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

## Qn 5:

In [21]:
array7=np.array([[1,2],[3,4],[5,6]])

In [22]:
array8=np.array([[10,20],[30,40],[50,60]])

In [23]:
np.hstack((array7,array8))

array([[ 1,  2, 10, 20],
       [ 3,  4, 30, 40],
       [ 5,  6, 50, 60]])

In [24]:
np.vstack((array7,array8))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [10, 20],
       [30, 40],
       [50, 60]])

## Qn 6:

In [25]:
array9 = np.array([[1,2,3],[4,5,6]])

In [26]:
array10 = np.array([[10,20,30],[40,50,60]])

In [27]:
np.append(array9,array10,axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30],
       [40, 50, 60]])

In [28]:
np.append(array9,array10,axis=1)

array([[ 1,  2,  3, 10, 20, 30],
       [ 4,  5,  6, 40, 50, 60]])

## Qn 7:

In [29]:
list1 = [[101,'ABC','abc.com','Chennai'],
        [102,'DEF','def.com','Banglore'],
        [103,'GHI','ghi.com','Delhi'],
        [104,'JKL','jkl.com','Mumbai'],
        [105,'MNO','mno.com','Rajasthan'],
        [106,'PQR','pqr.com','Hyderabad'],
        [107,'STU','stu.com','Pune'],
        [108,'VWX','vwx.com','Cochin']]

In [30]:
list1


[[101, 'ABC', 'abc.com', 'Chennai'],
 [102, 'DEF', 'def.com', 'Banglore'],
 [103, 'GHI', 'ghi.com', 'Delhi'],
 [104, 'JKL', 'jkl.com', 'Mumbai'],
 [105, 'MNO', 'mno.com', 'Rajasthan'],
 [106, 'PQR', 'pqr.com', 'Hyderabad'],
 [107, 'STU', 'stu.com', 'Pune'],
 [108, 'VWX', 'vwx.com', 'Cochin']]

In [31]:
df1=pd.DataFrame(list1,columns=['Employee ID','Employee Name','Email','City'])

In [32]:
df1

Employee ID Employee Name    Email       City
0          101           ABC  abc.com    Chennai
1          102           DEF  def.com   Banglore
2          103           GHI  ghi.com      Delhi
3          104           JKL  jkl.com     Mumbai
4          105           MNO  mno.com  Rajasthan
5          106           PQR  pqr.com  Hyderabad
6          107           STU  stu.com       Pune
7          108           VWX  vwx.com     Cochin

## Qn 8:

In [33]:
dict1 = {'Emp ID':[101,102,103,104],
        'Emp Name':['ABC','DEF','GHI','JKL'],
        'Email':['abc.com','def.com','ghi.com','jkl.com'],
        'City':['Chenni','Banglore','Delhi','Mumbai'],
        'Gender':['M','M','F','F'],
        'Role':['Dev','Support','Testing','Analyst'],
        'Experience':[1,2,3,4],
        'Rating':['A','B','A','C']}

In [34]:
df2 = pd.DataFrame(dict1)

In [35]:
df2


Emp ID Emp Name    Email      City Gender     Role  Experience Rating
0     101      ABC  abc.com    Chenni      M      Dev           1      A
1     102      DEF  def.com  Banglore      M  Support           2      B
2     103      GHI  ghi.com     Delhi      F  Testing           3      A
3     104      JKL  jkl.com    Mumbai      F  Analyst           4      C

## Qn 9:

In [37]:
df2.iloc[:2]

Emp ID Emp Name    Email      City Gender     Role  Experience Rating
0     101      ABC  abc.com    Chenni      M      Dev           1      A
1     102      DEF  def.com  Banglore      M  Support           2      B

In [41]:
df2.loc[:2,['Emp ID', 'Emp Name']]

Emp ID Emp Name
0     101      ABC
1     102      DEF
2     103      GHI

## Qn 10:

In [42]:
df2.notnull().sum()

Emp ID        4
Emp Name      4
Email         4
City          4
Gender        4
Role          4
Experience    4
Rating        4
dtype: int64

In [44]:
df2['Emp ID'].notnull().sum()

4

## Qn 11:

In [45]:
dict1 = {'Emp ID':[101,np.nan,103,104],
        'Emp Name':['ABC','DEF','GHI','JKL'],
        'Email':['abc.com','def.com','ghi.com','jkl.com'],
        'City':['Chenni','Banglore','Delhi','Mumbai'],
        'Gender':['M',np.nan,'F','F'],
        'Role':['Dev','Support','Testing','Analyst'],
        'Experience':[1,np.nan,3,4],
        'Rating':['A','B','A','C']}

In [46]:
df3 = pd.DataFrame(dict1)

In [47]:
df3

Emp ID Emp Name    Email      City Gender     Role  Experience Rating
0   101.0      ABC  abc.com    Chenni      M      Dev         1.0      A
1     NaN      DEF  def.com  Banglore    NaN  Support         NaN      B
2   103.0      GHI  ghi.com     Delhi      F  Testing         3.0      A
3   104.0      JKL  jkl.com    Mumbai      F  Analyst         4.0      C

In [48]:
df3.fillna(100)

Emp ID Emp Name    Email      City Gender     Role  Experience Rating
0   101.0      ABC  abc.com    Chenni      M      Dev         1.0      A
1   100.0      DEF  def.com  Banglore    100  Support       100.0      B
2   103.0      GHI  ghi.com     Delhi      F  Testing         3.0      A
3   104.0      JKL  jkl.com    Mumbai      F  Analyst         4.0      C

## Qn 12:

In [49]:
df4 = pd.DataFrame(dict1)

In [51]:
df4

Emp ID Emp Name    Email      City Gender     Role  Experience Rating
0   101.0      ABC  abc.com    Chenni      M      Dev         1.0      A
1     NaN      DEF  def.com  Banglore    NaN  Support         NaN      B
2   103.0      GHI  ghi.com     Delhi      F  Testing         3.0      A
3   104.0      JKL  jkl.com    Mumbai      F  Analyst         4.0      C

In [50]:
df4.dropna()

Emp ID Emp Name    Email    City Gender     Role  Experience Rating
0   101.0      ABC  abc.com  Chenni      M      Dev         1.0      A
2   103.0      GHI  ghi.com   Delhi      F  Testing         3.0      A
3   104.0      JKL  jkl.com  Mumbai      F  Analyst         4.0      C

## Qn 13:

In [52]:
df5 = pd.DataFrame([[25,'Black','SW',1],
                        [30,'Black','NW',1],
                        [45,'Red','NE',1],
                        [35,'Blond','SW',0],
                        [33,'Brown','SW',0],
                        [35,'Brown','NE',0],
                        [25,'Black','SW',0],
                        [52,'Brown','SE',0],
                        [21,'Blond','SW',1],
                        [24,'Blond','NE',0],
                        [48,'Black','SW',1],
                        [22,'Black','SW',0],
                        [27,'Brown','NE',0],
                        [28,'Black','SE',1],
                        [21,'Blond','SE',1],
                        [51,'Black','NW',0],
                        [23,'Brown','SE',1],                        
                       ]
                       ,columns =['AGE','HAIR COLOR','US REGION','VALIDATION'] )

In [53]:
df5

AGE HAIR COLOR US REGION  VALIDATION
0    25      Black        SW           1
1    30      Black        NW           1
2    45        Red        NE           1
3    35      Blond        SW           0
4    33      Brown        SW           0
5    35      Brown        NE           0
6    25      Black        SW           0
7    52      Brown        SE           0
8    21      Blond        SW           1
9    24      Blond        NE           0
10   48      Black        SW           1
11   22      Black        SW           0
12   27      Brown        NE           0
13   28      Black        SE           1
14   21      Blond        SE           1
15   51      Black        NW           0
16   23      Brown        SE           1

In [54]:
df5.groupby(['US REGION'])['AGE'].mean()

US REGION
NE    32.750000
NW    40.500000
SE    31.000000
SW    29.857143
Name: AGE, dtype: float64

In [68]:
df5.groupby(['HAIR COLOR'])['AGE'].sum().reset_index()

HAIR COLOR  AGE
0      Black  229
1      Blond  101
2      Brown  170
3        Red   45

In [66]:
df5.groupby(['HAIR COLOR'])['AGE','VALIDATION'].sum().reset_index()

<ipython-input-66-8ba15f6d609d>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df5.groupby(['HAIR COLOR'])['AGE','VALIDATION'].sum().reset_index()


HAIR COLOR  AGE  VALIDATION
0      Black  229           4
1      Blond  101           2
2      Brown  170           1
3        Red   45           1

In [69]:
df5.groupby(['US REGION'])['AGE'].mean()

US REGION
NE    32.750000
NW    40.500000
SE    31.000000
SW    29.857143
Name: AGE, dtype: float64

In [70]:
df5.groupby(['US REGION'])['AGE'].median()

US REGION
NE    31.0
NW    40.5
SE    25.5
SW    25.0
Name: AGE, dtype: float64

## Qn 14:

In [76]:
df6 = df5.loc[:7]
df7 = df5.loc[8:]

In [77]:
df6

AGE HAIR COLOR US REGION  VALIDATION
0   25      Black        SW           1
1   30      Black        NW           1
2   45        Red        NE           1
3   35      Blond        SW           0
4   33      Brown        SW           0
5   35      Brown        NE           0
6   25      Black        SW           0
7   52      Brown        SE           0

In [78]:
df7

AGE HAIR COLOR US REGION  VALIDATION
8    21      Blond        SW           1
9    24      Blond        NE           0
10   48      Black        SW           1
11   22      Black        SW           0
12   27      Brown        NE           0
13   28      Black        SE           1
14   21      Blond        SE           1
15   51      Black        NW           0
16   23      Brown        SE           1

In [79]:
df_Inner = df6.merge(df7, on='US REGION', how='inner')
df_Inner

AGE_x HAIR COLOR_x US REGION  VALIDATION_x  AGE_y HAIR COLOR_y  \
0      25        Black        SW             1     21        Blond   
1      25        Black        SW             1     48        Black   
2      25        Black        SW             1     22        Black   
3      35        Blond        SW             0     21        Blond   
4      35        Blond        SW             0     48        Black   
5      35        Blond        SW             0     22        Black   
6      33        Brown        SW             0     21        Blond   
7      33        Brown        SW             0     48        Black   
8      33        Brown        SW             0     22        Black   
9      25        Black        SW             0     21        Blond   
10     25        Black        SW             0     48        Black   
11     25        Black        SW             0     22        Black   
12     30        Black        NW             1     51        Black   
13     45          Red        NE             1     24        Blond   
14     45          Red        NE             1     27        Brown   
15     35        Brown        NE             0     24        Blond   
16     35        Brown        NE             0     27        Brown   
17     52        Brown        SE             0     28        Black   
18     52        Brown        SE             0     21        Blond   
19     52        Brown        SE             0     23        Brown   

    VALIDATION_y  
0              1  
1              1  
2              0  
3              1  
4              1  
5              0  
6              1  
7              1  
8              0  
9              1  
10             1  
11             0  
12             0  
13             0  
14             0  
15             0  
16             0  
17             1  
18             1  
19             1

In [82]:
df_Left = df6.merge(df7, on='US REGION', how='left')
df_Left

AGE_x HAIR COLOR_x US REGION  VALIDATION_x  AGE_y HAIR COLOR_y  \
0      25        Black        SW             1     21        Blond   
1      25        Black        SW             1     48        Black   
2      25        Black        SW             1     22        Black   
3      30        Black        NW             1     51        Black   
4      45          Red        NE             1     24        Blond   
5      45          Red        NE             1     27        Brown   
6      35        Blond        SW             0     21        Blond   
7      35        Blond        SW             0     48        Black   
8      35        Blond        SW             0     22        Black   
9      33        Brown        SW             0     21        Blond   
10     33        Brown        SW             0     48        Black   
11     33        Brown        SW             0     22        Black   
12     35        Brown        NE             0     24        Blond   
13     35        Brown        NE             0     27        Brown   
14     25        Black        SW             0     21        Blond   
15     25        Black        SW             0     48        Black   
16     25        Black        SW             0     22        Black   
17     52        Brown        SE             0     28        Black   
18     52        Brown        SE             0     21        Blond   
19     52        Brown        SE             0     23        Brown   

    VALIDATION_y  
0              1  
1              1  
2              0  
3              0  
4              0  
5              0  
6              1  
7              1  
8              0  
9              1  
10             1  
11             0  
12             0  
13             0  
14             1  
15             1  
16             0  
17             1  
18             1  
19             1

In [83]:
df_Right = df6.merge(df7, on='US REGION', how='right')
df_Right

AGE_x HAIR COLOR_x US REGION  VALIDATION_x  AGE_y HAIR COLOR_y  \
0      25        Black        SW             1     21        Blond   
1      35        Blond        SW             0     21        Blond   
2      33        Brown        SW             0     21        Blond   
3      25        Black        SW             0     21        Blond   
4      45          Red        NE             1     24        Blond   
5      35        Brown        NE             0     24        Blond   
6      25        Black        SW             1     48        Black   
7      35        Blond        SW             0     48        Black   
8      33        Brown        SW             0     48        Black   
9      25        Black        SW             0     48        Black   
10     25        Black        SW             1     22        Black   
11     35        Blond        SW             0     22        Black   
12     33        Brown        SW             0     22        Black   
13     25        Black        SW             0     22        Black   
14     45          Red        NE             1     27        Brown   
15     35        Brown        NE             0     27        Brown   
16     52        Brown        SE             0     28        Black   
17     52        Brown        SE             0     21        Blond   
18     30        Black        NW             1     51        Black   
19     52        Brown        SE             0     23        Brown   

    VALIDATION_y  
0              1  
1              1  
2              1  
3              1  
4              0  
5              0  
6              1  
7              1  
8              1  
9              1  
10             0  
11             0  
12             0  
13             0  
14             0  
15             0  
16             1  
17             1  
18             0  
19             1

## Qn 15:

In [84]:
pd.concat([df6,df7], axis = 0)

AGE HAIR COLOR US REGION  VALIDATION
0    25      Black        SW           1
1    30      Black        NW           1
2    45        Red        NE           1
3    35      Blond        SW           0
4    33      Brown        SW           0
5    35      Brown        NE           0
6    25      Black        SW           0
7    52      Brown        SE           0
8    21      Blond        SW           1
9    24      Blond        NE           0
10   48      Black        SW           1
11   22      Black        SW           0
12   27      Brown        NE           0
13   28      Black        SE           1
14   21      Blond        SE           1
15   51      Black        NW           0
16   23      Brown        SE           1

In [87]:
pd.concat([df6,df7], axis = 1)

AGE HAIR COLOR US REGION  VALIDATION   AGE HAIR COLOR US REGION  \
0   25.0      Black        SW         1.0   NaN        NaN       NaN   
1   30.0      Black        NW         1.0   NaN        NaN       NaN   
2   45.0        Red        NE         1.0   NaN        NaN       NaN   
3   35.0      Blond        SW         0.0   NaN        NaN       NaN   
4   33.0      Brown        SW         0.0   NaN        NaN       NaN   
5   35.0      Brown        NE         0.0   NaN        NaN       NaN   
6   25.0      Black        SW         0.0   NaN        NaN       NaN   
7   52.0      Brown        SE         0.0   NaN        NaN       NaN   
8    NaN        NaN       NaN         NaN  21.0      Blond        SW   
9    NaN        NaN       NaN         NaN  24.0      Blond        NE   
10   NaN        NaN       NaN         NaN  48.0      Black        SW   
11   NaN        NaN       NaN         NaN  22.0      Black        SW   
12   NaN        NaN       NaN         NaN  27.0      Brown        NE   
13   NaN        NaN       NaN         NaN  28.0      Black        SE   
14   NaN        NaN       NaN         NaN  21.0      Blond        SE   
15   NaN        NaN       NaN         NaN  51.0      Black        NW   
16   NaN        NaN       NaN         NaN  23.0      Brown        SE   

    VALIDATION  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN  
5          NaN  
6          NaN  
7          NaN  
8          1.0  
9          0.0  
10         1.0  
11         0.0  
12         0.0  
13         1.0  
14         1.0  
15         0.0  
16         1.0