## Qn 1:

In [3]:
name = input('Enter your name ')
age = int(input('Enter your age '))
year = 2022 + (100-int(age))
print(name, 'will turn 100 years old in the year', year)

Enter your name Vijay
Enter your age 27
Vijay will turn 100 years old in the year 2095


## Qn 2:

In [8]:
import numpy as np
import pandas as pd

In [15]:
dict1 = {'Age':[25,30,45,35,33,35,25,52,21,24,48,22,27,28,21,51,23],
            'Hair Color':['Black','Black','Red','Blond','Brown','Brown','Black','Brown','Blond','Blond','Black','Black','Brown','Black','Blond','Black','Brown'],
            'US Region':['Southwest','Northwest','Northeast','Southwest','Southwest','Northeast','Southwest','Southeast','Southwest','Northeast','Southwest','Southwest','Northeast','Southeast','Southeast','Northwest','Southeast'],
            'Validation':[1,1,1,0,0,0,0,0,1,0,1,0,0,1,1,0,1]  }

In [16]:
df1 = pd.DataFrame(dict1)

In [17]:
df1.groupby(['US Region'])['Age'].mean()

US Region
Northeast    32.750000
Northwest    40.500000
Southeast    31.000000
Southwest    29.857143
Name: Age, dtype: float64

## Qn 3:

In [18]:
list1 = [[101,'ABC','abc.com','Chennai'],
        [102,'DEF','def.com','Banglore'],
        [103,'GHI','ghi.com','Delhi'],
        [104,'JKL','jkl.com','Mumbai'],
        [105,'MNO','mno.com','Rajasthan'],
        [106,'PQR','pqr.com','Hyderabad'],
        [107,'STU','stu.com','Pune'],
        [108,'VWX','vwx.com','Cochin']]

In [19]:
df2=pd.DataFrame(list1,columns=['Employee ID','Employee Name','Email','City'])

## Qn 4:

In [20]:
df5 = pd.DataFrame([[25,'Black','SW',1],
                        [30,'Black','NW',1],
                        [45,'Red','NE',1],
                        [35,'Blond','SW',0],
                        [33,'Brown','SW',0],
                        [35,'Brown','NE',0],
                        [25,'Black','SW',0],
                        [52,'Brown','SE',0],
                        [21,'Blond','SW',1],
                        [24,'Blond','NE',0],
                        [48,'Black','SW',1],
                        [22,'Black','SW',0],
                        [27,'Brown','NE',0],
                        [28,'Black','SE',1],
                        [21,'Blond','SE',1],
                        [51,'Black','NW',0],
                        [23,'Brown','SE',1],                        
                       ]
                       ,columns =['AGE','HAIR COLOR','US REGION','VALIDATION'] )

In [21]:
df6 = df5.loc[:7]
df7 = df5.loc[8:]

In [22]:
df_Inner = df6.merge(df7, on='US REGION', how='inner')
df_Inner

AGE_x HAIR COLOR_x US REGION  VALIDATION_x  AGE_y HAIR COLOR_y  \
0      25        Black        SW             1     21        Blond   
1      25        Black        SW             1     48        Black   
2      25        Black        SW             1     22        Black   
3      35        Blond        SW             0     21        Blond   
4      35        Blond        SW             0     48        Black   
5      35        Blond        SW             0     22        Black   
6      33        Brown        SW             0     21        Blond   
7      33        Brown        SW             0     48        Black   
8      33        Brown        SW             0     22        Black   
9      25        Black        SW             0     21        Blond   
10     25        Black        SW             0     48        Black   
11     25        Black        SW             0     22        Black   
12     30        Black        NW             1     51        Black   
13     45          Red        NE             1     24        Blond   
14     45          Red        NE             1     27        Brown   
15     35        Brown        NE             0     24        Blond   
16     35        Brown        NE             0     27        Brown   
17     52        Brown        SE             0     28        Black   
18     52        Brown        SE             0     21        Blond   
19     52        Brown        SE             0     23        Brown   

    VALIDATION_y  
0              1  
1              1  
2              0  
3              1  
4              1  
5              0  
6              1  
7              1  
8              0  
9              1  
10             1  
11             0  
12             0  
13             0  
14             0  
15             0  
16             0  
17             1  
18             1  
19             1

In [23]:
df_Left = df6.merge(df7, on='US REGION', how='left')
df_Left

AGE_x HAIR COLOR_x US REGION  VALIDATION_x  AGE_y HAIR COLOR_y  \
0      25        Black        SW             1     21        Blond   
1      25        Black        SW             1     48        Black   
2      25        Black        SW             1     22        Black   
3      30        Black        NW             1     51        Black   
4      45          Red        NE             1     24        Blond   
5      45          Red        NE             1     27        Brown   
6      35        Blond        SW             0     21        Blond   
7      35        Blond        SW             0     48        Black   
8      35        Blond        SW             0     22        Black   
9      33        Brown        SW             0     21        Blond   
10     33        Brown        SW             0     48        Black   
11     33        Brown        SW             0     22        Black   
12     35        Brown        NE             0     24        Blond   
13     35        Brown        NE             0     27        Brown   
14     25        Black        SW             0     21        Blond   
15     25        Black        SW             0     48        Black   
16     25        Black        SW             0     22        Black   
17     52        Brown        SE             0     28        Black   
18     52        Brown        SE             0     21        Blond   
19     52        Brown        SE             0     23        Brown   

    VALIDATION_y  
0              1  
1              1  
2              0  
3              0  
4              0  
5              0  
6              1  
7              1  
8              0  
9              1  
10             1  
11             0  
12             0  
13             0  
14             1  
15             1  
16             0  
17             1  
18             1  
19             1

In [24]:
df_Right = df6.merge(df7, on='US REGION', how='right')
df_Right

AGE_x HAIR COLOR_x US REGION  VALIDATION_x  AGE_y HAIR COLOR_y  \
0      25        Black        SW             1     21        Blond   
1      35        Blond        SW             0     21        Blond   
2      33        Brown        SW             0     21        Blond   
3      25        Black        SW             0     21        Blond   
4      45          Red        NE             1     24        Blond   
5      35        Brown        NE             0     24        Blond   
6      25        Black        SW             1     48        Black   
7      35        Blond        SW             0     48        Black   
8      33        Brown        SW             0     48        Black   
9      25        Black        SW             0     48        Black   
10     25        Black        SW             1     22        Black   
11     35        Blond        SW             0     22        Black   
12     33        Brown        SW             0     22        Black   
13     25        Black        SW             0     22        Black   
14     45          Red        NE             1     27        Brown   
15     35        Brown        NE             0     27        Brown   
16     52        Brown        SE             0     28        Black   
17     52        Brown        SE             0     21        Blond   
18     30        Black        NW             1     51        Black   
19     52        Brown        SE             0     23        Brown   

    VALIDATION_y  
0              1  
1              1  
2              1  
3              1  
4              0  
5              0  
6              1  
7              1  
8              1  
9              1  
10             0  
11             0  
12             0  
13             0  
14             0  
15             0  
16             1  
17             1  
18             0  
19             1

In [25]:
pd.concat([df6,df7], axis = 0)

AGE HAIR COLOR US REGION  VALIDATION
0    25      Black        SW           1
1    30      Black        NW           1
2    45        Red        NE           1
3    35      Blond        SW           0
4    33      Brown        SW           0
5    35      Brown        NE           0
6    25      Black        SW           0
7    52      Brown        SE           0
8    21      Blond        SW           1
9    24      Blond        NE           0
10   48      Black        SW           1
11   22      Black        SW           0
12   27      Brown        NE           0
13   28      Black        SE           1
14   21      Blond        SE           1
15   51      Black        NW           0
16   23      Brown        SE           1

In [26]:
pd.concat([df6,df7], axis = 1)

AGE HAIR COLOR US REGION  VALIDATION   AGE HAIR COLOR US REGION  \
0   25.0      Black        SW         1.0   NaN        NaN       NaN   
1   30.0      Black        NW         1.0   NaN        NaN       NaN   
2   45.0        Red        NE         1.0   NaN        NaN       NaN   
3   35.0      Blond        SW         0.0   NaN        NaN       NaN   
4   33.0      Brown        SW         0.0   NaN        NaN       NaN   
5   35.0      Brown        NE         0.0   NaN        NaN       NaN   
6   25.0      Black        SW         0.0   NaN        NaN       NaN   
7   52.0      Brown        SE         0.0   NaN        NaN       NaN   
8    NaN        NaN       NaN         NaN  21.0      Blond        SW   
9    NaN        NaN       NaN         NaN  24.0      Blond        NE   
10   NaN        NaN       NaN         NaN  48.0      Black        SW   
11   NaN        NaN       NaN         NaN  22.0      Black        SW   
12   NaN        NaN       NaN         NaN  27.0      Brown        NE   
13   NaN        NaN       NaN         NaN  28.0      Black        SE   
14   NaN        NaN       NaN         NaN  21.0      Blond        SE   
15   NaN        NaN       NaN         NaN  51.0      Black        NW   
16   NaN        NaN       NaN         NaN  23.0      Brown        SE   

    VALIDATION  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN  
5          NaN  
6          NaN  
7          NaN  
8          1.0  
9          0.0  
10         1.0  
11         0.0  
12         0.0  
13         1.0  
14         1.0  
15         0.0  
16         1.0

## Qn 5:

In [27]:
list1 = [1,2,3]
tuple1 = (1,2,3)

In [28]:
list1[2]=10  #mutable

In [29]:
tuple1[2]=10  #immutable

TypeError: 'tuple' object does not support item assignment

## Qn 6:

In [30]:
array1 = np.array([1,5,3,100,4,48])

In [32]:
np.mean(array1)

26.833333333333332

In [33]:
np.median(array1)

4.5

In [34]:
np.std(array1)

36.59424666377065

## Qn 7:

In [35]:
list1 = [1,1,2,2,3,4]

In [36]:
list1 = list(set(list1))

In [37]:
list1

[1, 2, 3, 4]

## Qn 8:

In [38]:
# Map function used to perform a specific operation on all the values in a collection

list2 = list(range(10))
list3 = list(map(lambda x:(x*x),list2))
print(list3)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


## Qn 9:

In [39]:
# Pass is used to skip the loop when a condition is met but it doesnt stop the exection of loop

for num in range(10):
    if num == 2:
        pass
    else:
        print(num)

0
1
3
4
5
6
7
8
9


## Qn 10:

In [40]:
# Vstack is used to combine arrays in vertical/column wise

array2=np.array([[1,2,3],[4,5,6]])
array3=np.array([[7,8,9],[10,11,12]])
print (np.vstack((array2,array3)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
